### ISSUE TITLE
P2 with 3080 has memory leak

### ISSUE THREAD

**Issue by gavin-ygy** [filecoin-project/rust-fil-proofs#1472] opened 2021-06-14 05:26 UTC
### lotus-worker version ：v1.10-rc2 + rust-fil-proofs v8.0.1.
       GPU:3080 + v460.80
       At first,  all the three workers  process P2 ok. But after finishing a few P2,  the workers begin to report  GPUError and can't process P2 normally:
---
thread '<unnamed>' panicked at 'failed to add columns: GPUError("Ocl(\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueWriteBuffer  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueWriteBuffer.html#errors  \n\n############################################################################# \n)")', /home/vm/test/test-v1.11/storage-proofs-porep-8.0.0/src/stacked/vanilla/proof.rs:578:38
stack backtrace:
   0:          0x248bfe0 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:          0x248bfe0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x248bfe0 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:67:5
   3:          0x248bfe0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:46:22
   4:          0x24fc24f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/fmt/mod.rs:1094:17
   5:          0x2480775 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/io/mod.rs:1580:15
   6:          0x248fd3b - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:49:5
   7:          0x248fd3b - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:36:9
   8:          0x248fd3b - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:208:50
   9:          0x248f81d - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:225:9
  10:          0x249042d - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:591:17
  11:          0x2490027 - std::panicking::begin_panic_handler::{{closure}}::ha376ab85d95a000e
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:497:13
  12:          0x248c49c - std::sys_common::backtrace::__rust_end_short_backtrace::h6795c8afdd1a77e6
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:141:18
  13:          0x248ff89 - rust_begin_unwind
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:493:5

**Comment by cryptonemo** [comment] 2021-07-07 11:51
Any updates here?  Can you describe your runtime configuration a bit more?  We're trying to find why some miners are running out of GPU memory, but many aren't.

**Comment by gavin-ygy** [comment] 2021-07-14 01:32
the  release v1.10  still has the issues.  i use a shell scripts to catch the log which find the "GPUError" and force to reboot the p2 worker:)

**Comment by cryptonemo** [comment] 2021-07-14 14:42
Similar (if not the same) issue as #1476 and #1478

Can you monitor your GPU RAM during the runs and try to determine where the memory is not freed if this is the case?  We also need to determine that something using GPU RAM doesn't allow something else to try to use it at the same time causing an overallocation.

**Comment by Wondertan** [comment] 2021-08-04 06:46
Starting to have the same issue regularly on 3090. However, the root panic is slightly different but still looks like a mentioned leak on `rust-fil-proofs v8.0.1`
```
Error executing function: clEnqueueWriteBuffer 
Status error code: CL_OUT_OF_RESOURCES (-5)
```

The problem is that I am not running two or more workers per GPU, but one only, so this is indeed not a valid behavior. Also, it completely throttles the whole sector precessing once this happens, as the lock is not released and subsequent `PoisonErrors` get thrown. 

> Can you monitor your GPU RAM during the runs and try to determine where the memory is not freed if this is the case? 

It is not possible in my case unless you can recommend a tool to do so. Otherwise, I would need to sit and monitor `htop` 24 hours or more straight to catch a PC2 with such behavior. Most of the time, everything is alright, but once in 1-2 days I wake up and see that I have more than 30 sectors queued up for PC1, as they fall back from failed PC2. Cleaning such a mess is tedious and commenting `gpu_lock`, as mentioned [here](https://github.com/filecoin-project/rust-fil-proofs/issues/1478#issuecomment-879652466) is not the right solution.

**Comment by cryptonemo** [comment] 2021-08-04 11:44
I was referring to tools like `nvtop` or `nvidia-smi` (the latter should be able to be logged with timestamps).

**Comment by cryptonemo** [comment] 2021-08-04 15:19
Possible solution worth looking into? https://github.com/filecoin-project/lotus/issues/6980#issuecomment-892743688

**Comment by Wondertan** [comment] 2021-08-10 11:44
@cryptonemo, so I've been running worker with `render` group for 4 days already and it seems like the problem disappeared. I am still not 100% sure if the solution fixed that though. Need to run it for more time, but the existing results look promising.

**Comment by cryptonemo** [comment] 2021-08-10 11:46
This is great news, thanks for the follow-up!  Please keep us posted (cc: @jennijuju)

**Comment by vmx** [comment] 2023-09-12 09:50
The original issue has been resolved, hence closing this issue.

**Closed by vmx** 2023-09-12 09:50 UTC
