### ISSUE TITLE
Cannot get device list for platform: Clover!

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/rust-fil-proofs#1366] opened 2020-11-15 18:06 UTC
Issue is back on Lotus 1.1.3. After upgrading, my PC2s are just stuck for 24+ hours, no progress whatsoever. The only log I've need is `generating tree c using the GPU` followed by `Cannot get device list for platform: Clover!`.

**Comment by porcuquine** [comment] 2020-11-15 19:45
This is warning isn't a problem, but it does help identify where things might have gone wrong. I'm looking now.

**Comment by karalabe** [comment] 2020-11-15 21:03
I think I have some more info. I was running with 

```
FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
FIL_PROOFS_USE_GPU_TREE_BUILDER=1
BELLMAN_NO_GPU=true
```

This worked very well in Lotus 1.1.2. The aim was to force PC2 to run on the GPU (multiple ones concurrently (I hacked the CPU thread count to allow it)) and the C2 to be done by the CPU (because I can run 2x without even saturating my CPU). This setup worked very well and I could do quite a few PC2 concurrently (actually 3-4 without a performance hit).

The new release however just stuck waiting on PC2. Perhaps it started interpreting `BELLMAN_NO_GPU` for PC2 too and somehow managed to "want to run on the GPU but no GPU is present?". If removed the `BELLMAN_NO_GPU=true` flag then PC2 get scheduled, but only 1, thus my concurrency drops by /4 at least. Also this ends up C2 running on the GPU, which I don't want.

Sooo, can I pls get my GPU concurrency back somehow?

I can definitely say for sure that 1 single PC2 underutilizes my GPU even when crunching at "max speed". RAM usage is about 3GB out of 10, peak power usage is ~160-170W out of 340. With lotus 1.1.2 I could easily draw the full 340W capacity whilst running with 7-8-9GB RAM usage, so it definitely used my hardware a lot better (with GPU tracking disabled, because otherwise the scheduler wants to be too smart for itself).

Would it be possible somehow to specify the resources individual tasks consume off of the GPU too and permit multiple ones to be scheduled?

**Comment by porcuquine** [comment] 2020-11-15 21:27
Some notes:

I was able to reproduce this on `master`, but I don't think it's *directly* the same as you are experiencing.

`master` has code introduces changes which hopefully will improve the tree-building concurrency in general (from #1335). I have a PR (#1367), which patches the problem. I'm hopeful that simply moving to the new code will make things better.

It will be useful to find out what you observe once you are running this latest (not yet released) code. That is probably the best starting point for diagnosing any remaining problems.

**Comment by Shekelme** [comment] 2020-11-16 02:53
In my case even the benchmark can not start PC2, so I have no initialized the miner yet. The logs I have:

```
2020-11-15T10:17:55.947 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
2020-11-15T10:17:56.001+0300	INFO	lotus-bench	lotus-bench/main.go:531	[1] Running replication(2)...
2020-11-15T10:17:56.027 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2020-11-15T10:17:56.031 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2020-11-15T10:17:56.032 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2020-11-15T10:17:56.034 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2020-11-15T10:17:56.037 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2020-11-15T10:17:56.038 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2020-11-15T10:17:56.038 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
2020-11-15T10:17:56.050 INFO neptune::cl > getting context for ~Index(0)
2020-11-15T10:17:56.271 WARN neptune::cl > Cannot get device list for platform: Clover!
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/don_genaro/.cargo/registry/src/github.com-1ecc6299db9ec823/neptune-2.1.1/src/cl.rs:252:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /home/don_genaro/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.3.0/src/stacked/vanilla/proof.rs:502:34
2020-11-15T10:18:07.039+0300	WARN	lotus-bench	lotus-bench/main.go:91	failed to run seals:
    main.glob..func3
        /home/don_genaro/lotus/cmd/lotus-bench/main.go:251
  - commit:
    main.runSeals.func1.1
        /home/don_genaro/lotus/cmd/lotus-bench/main.go:534
  - presealing sector 1 ():
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /home/don_genaro/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:477
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase2
    	/home/don_genaro/lotus/extern/filecoin-ffi/proofs.go:321
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
    	/home/don_genaro/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:475
    main.runSeals.func1.1
    	/home/don_genaro/lotus/cmd/lotus-bench/main.go:532
    main.runSeals.func1
    	/home/don_genaro/lotus/cmd/lotus-bench/main.go:643
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1374
```

Lotus version (some hacks related CPU and RAM resources, nothing related to GPU, no restrictions):

```
Daemon:  1.1.3+git.15fe726e6.dirty+api0.17.0
Local: lotus version 1.1.3+git.15fe726e6.dirty
```

Ubuntu 20.10, Nvidia driver: 450.80.02

Environment variables:
RUST_LOG=info
FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
FIL_PROOFS_USE_GPU_TREE_BUILDER=1
FIL_PROOFS_MAXIMIZE_CACHING=1
BELLMAN_CUSTOM_GPU=GeForce GTX 1070 Ti:2432

**Comment by porcuquine** [comment] 2020-11-16 16:04
@shekelme What does `clinfo` tell you? The error you are seeing indicates that no AMD or Nvidia GPUs are accessible.

**Comment by yydfjt** [comment] 2020-11-21 09:37
Dmesg shows： [ 609.751833] NVRM: Xid (PCI:0000:01:00): 13, pid=3309, Graphics SM Warp Exception on (GPC 1, TPC 0, SM 0): Out Of Range Address [ 609.751912] NVRM: Xid (PCI:0000:01:00): 13, pid=3309, Graphics Exception: ESR 0x50c730=0xc01000e 0x50c734=0x20 0x50c728=0x4c1eb72 0x50c72c=0x174 [ 609.752733] NVRM: Xid (PCI:0000:01:00): 43, pid=3265, Ch 00000；

Then PC2 stuck

**Comment by karalabe** [comment] 2020-11-21 17:22
My PC2s got stuck today too, last GPU logs were

```
f","caller":"/root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:1033","msg":"tree_c done"}
f","caller":"/root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:1060","msg":"building tree_r_last"}
f","caller":"/root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:702","msg":"generating tree r last using the GPU"}
/src/github.com-1ecc6299db9ec823/neptune-2.2.0/src/cl.rs:288","msg":"getting context for ~Index(0)"}
/src/github.com-1ecc6299db9ec823/neptune-2.2.0/src/cl.rs:196","msg":"Cannot get device list for platform: Clover!"}
```

(cut off the prefixes). No error, no crash, just hangs.

In `dmesg` I have a following error:

```
[612838.206929] NVRM: GPU at PCI:0000:c1:00: GPU-cc3e318b-f992-c826-25bf-4f19259f23c9
[612838.206932] NVRM: GPU Board Serial Number: 
[612838.206934] NVRM: Xid (PCI:0000:c1:00): 13, pid=33887, Graphics SM Warp Exception on (GPC 2, TPC 0, SM 0): Out Of Range Address
[612838.207216] NVRM: Xid (PCI:0000:c1:00): 13, pid=33887, Graphics Exception: ESR 0x514730=0xc01000e 0x514734=0x20 0x514728=0xc81eb60 0x51472c=0x1174
[612838.207934] NVRM: Xid (PCI:0000:c1:00): 43, pid=32918, Ch 00000008
```

**Comment by karalabe** [comment] 2020-11-21 17:26
Restarted my miner, got a warning from `dmesg`:

```
[623779.672588] resource sanity check: requesting [mem 0x000c0000-0x000fffff], which spans more than PCI Bus 0000:00 [mem 0x000c0000-0x000dffff window]
[623779.672710] caller os_map_kernel_space.part.13+0x7d/0x80 [nvidia] mapping multiple BARs
```

Maybe this can be traced to be the culprit, lotus trying to address more video RAM than available?

**Comment by Storage-Hive** [comment] 2020-12-04 12:13
I had similar issue, was able to resolve it by removing the mesa libraries:
rpm -e mesa-libOpenCL mesa-libOpenCL-devel
After that the Clover messages went away and system is working well.

**Comment by porcuquine** [comment] 2020-12-04 17:58
Thanks, @Storage-Hive.

Given this report, I recommend everyone experiencing problems try removing mesa as suggested:

```
rpm -e mesa-libOpenCL mesa-libOpenCL-devel
```

I'm sure that will get rid of the warning. If it also fixes any problems people were having, that will be great news — so please report back either way.

**Comment by vmx** [comment] 2023-05-26 09:42
The issue seems to be fixed, and also the GPU changed a lot since then. Hence I'm closing this issue.

**Closed by vmx** 2023-05-26 09:42 UTC
Labels: gpu
