### ISSUE TITLE
compile error:error[E0433]: failed to resolve: could not find `arch` in `self`

### ISSUE THREAD

**Issue by AndyChen1984** [filecoin-project/rust-fil-proofs#882] opened 2019-09-18 00:14 UTC
rustc --version
rustc 1.38.0-nightly (2d1a551e1 2019-08-08)

 cargo --version
cargo 1.38.0-nightly (42a8c0adf 2019-08-07)

root@localhost:~/go_src_filecoin/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs# git log
commit d0e0c366c966e1992346c669e75d98010a5fb8a9 (HEAD, tag: d0e0c366c966e199)
Author: laser <l@s3r.me>
Date:   Thu Aug 22 17:00:53 2019 -0700

    need release binaries

commit 17900d454f2b46f8ff93a08b5e621db0bc327255 (tag: filecoin-proofs-0.6.4)
Author: laser <l@s3r.me>
Date:   Thu Aug 22 15:10:58 2019 -0700

    chore(filecoin-proofs): release 0.6.4

### Description
root@localhost:~/go_src_filecoin/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs# cargo build --release --all 
    Updating crates.io index
       Fetch [                                                       ]   0.00%                                                                                           Downloading 1 crate                                                                                                                                                     Downloading 1 crate, remaining bytes: 18.0 KB                                                                                                                            Downloaded merkletree v0.10.0
 Downloading 0 crates                                                                                                                                                    Downloading 1 crate                                                                                                                                                     Downloading 1 crate, remaining bytes: 12.4 KB                                                                                                                            Downloaded positioned-io v0.2.2
 Downloading 0 crates                                                                                                                                                    Downloading 1 crate                                                                                                                                                      Downloaded byteorder v0.5.3
 Downloading 0 crates                                                                                                                                                      Compiling byteorder v0.5.3
   Compiling raw-cpuid v6.1.0
   Compiling serde_derive v1.0.101
   Compiling heim-derive v0.0.5
    Building [=========================================>             ] 280/364: raw-cpuid, byteorder, serde_derive, heim-derive                                         error[E0433]: failed to resolve: could not find `arch` in `self`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-6.1.0/src/lib.rs:50:37
   |
50 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
   |                                     ^^^^ could not find `arch` in `self`

**Comment by dignifiedquire** [comment] 2019-09-18 05:52
what OS are you on? looks like this is an issue with the heim crate

**Comment by AndyChen1984** [comment] 2019-09-23 00:08
> what OS are you on? looks like this is an issue with the heim crate

root@localhost:~/go_src_filecoin/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs# uname -a
Linux localhost 4.14.83 #1 SMP PREEMPT Wed May 29 22:53:13 CST 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by pinkethan** [comment] 2019-12-03 06:30
I have the same problem.
$ rustc --version
rustc 1.40.0-nightly (1423bec54 2019-11-05)
$ cargo --version
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)
$ uname -a
Linux debian-gnu-linux-vm 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

**Description**
$ cargo build --target=mips64-unknown-linux-gnuabi64
   Compiling aes v0.3.2
   Compiling tempfile v3.1.0
   Compiling thiserror v1.0.6
error[E0433]: failed to resolve: could not find `arch` in `self`
  --> /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.3/src/lib.rs:50:37
   |
50 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
   |                                     ^^^^ could not find `arch` in `self`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.

**Comment by dignifiedquire** [comment] 2019-12-05 18:39
@pinkethan you are trying to build for `mips64` that is not a currently supported target I am afraid, and from the looks of it some of our depenencies work with it.

**Comment by dignifiedquire** [comment] 2019-12-05 18:40
it seems in both cases the issue is from this library https://github.com/gz/rust-cpuid

**Comment by pinkethan** [comment] 2019-12-16 02:45
> it seems in both cases the issue is from this library https://github.com/gz/rust-cpuid

Thanks for your information.

**Comment by dignifiedquire** [comment] 2020-03-02 14:12
Closing for now

**Closed by dignifiedquire** 2020-03-02 14:12 UTC
