### ISSUE TITLE
Can not replicate 1GB sectors anymore

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#713] opened 2019-06-29 10:38 UTC
Running a replication results in this output atm

```
Jun 28 17:20:56.236 INFO using parents cache of unlimited size, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storag
e-proofs/src/zigzag_graph.rs:75 storage_proofs::zigzag_graph
running replicate
Jun 28 17:20:56.904 INFO encoding, layer {}: 0, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/lay
ered_drgporep.rs:495 storage_proofs::layered_drgporep
thread '<unnamed>' panicked at 'index 1517125600 out of range for slice of length 1073741824', src/libcore/slice/mod.rs:2569:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                                                                 [7/841]
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2569
   9: <merkletree::merkle::MmapStore<E> as merkletree::merkle::Store<E>>::read_at
  10: merkletree::merkle::MerkleTree<T,A,K>::build
  11: <merkletree::merkle::MerkleTree<T,A,K> as rayon::iter::FromParallelIterator<T>>::from_par_iter
  12: storage_proofs::drgraph::Graph::merkle_tree_aux
  13: storage_proofs::layered_drgporep::Layers::transform_and_replicate_layers::{{closure}}::{{closure}}::{{closure}}
```

**Comment by porcuquine** [comment] 2019-06-29 10:51
Hmmm… Let's git bisect to find out when this broke and also add a regression test so it doesn't happen again. Sorry to be brief.

**Comment by dignifiedquire** [comment] 2019-06-29 14:40
Commands to reproduce: https://github.com/filecoin-project/replication-game/blob/seeded-porep/Dockerfile#L1-L2

**Comment by schomatis** [comment] 2019-06-29 23:50
Couldn't reproduce it, although there probably _is_ a bug somewhere. @dignifiedquire  could you help me isolate and reduce the use case please? Replicating 1GiB took 2+ hours on an 8-core machine (if you're not available I'll try to do it myself but I'm prioritizing the spec work at the moment). For now it may help to rebase https://github.com/filecoin-project/rust-fil-proofs/tree/seeded-porep on top of the `0.3` releases (https://github.com/filecoin-project/rust-fil-proofs/commit/adfc0fc6c457b4e8410a3255f8f973f8635bbfad) which used `merkletree v0.6.0` (assuming the bug lies in the latest changes to optimize memory there).

--------------------------------------

Attempt to reproduce:

```bash
git clone https://github.com/filecoin-project/replication-game
cd replication-game/
git checkout seeded-porep 
git rev-parse --short HEAD
# 2b54b31
docker build --tag replication-game .
docker run -it -v `pwd`:/code/ replication-game
```

```bash
   Compiling storage-proofs v0.3.0 (https://github.com/filecoin-project/rust-fil-proofs?branch=seeded-porep#e1f6f322)
   Compiling rocket_contrib v0.4.1
   Compiling filecoin-proofs v0.3.0 (https://github.com/filecoin-project/rust-fil-proofs?branch=seeded-porep#e1f6f322)
   Compiling replication-game v0.1.0 (/code)
warning: unused `#[macro_use]` import
 --> src/lib.rs:3:1
  |
3 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: type alias is never used: `ApiResult`
 --> src/error.rs:9:1
  |
9 | pub type ApiResult<T> = Result<T, ApiError>;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

    Finished release [optimized] target(s) in 6m 44s
getting seed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    442      0 --:--:-- --:--:-- --:--:--   443
generating fake data
running setup
Jun 29 20:04:51.736 INFO using parents cache of unlimited size, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/zigzag_graph.rs:75 storage_proofs::zigzag_graph
running replicate
Jun 29 20:04:52.763 INFO encoding, layer {}: 0, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 20:25:43.632 INFO encoding, layer {}: 1, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 20:46:19.713 INFO encoding, layer {}: 2, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 20:57:54.712 INFO encoding, layer {}: 3, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 21:09:28.304 INFO encoding, layer {}: 4, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 21:20:57.090 INFO encoding, layer {}: 5, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 21:32:34.785 INFO encoding, layer {}: 6, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 21:44:10.480 INFO encoding, layer {}: 7, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 21:55:36.833 INFO encoding, layer {}: 8, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
Jun 29 22:07:06.429 INFO encoding, layer {}: 9, root: storage-proofs, place: /root/.cargo/git/checkouts/rust-fil-proofs-0521dfc2b7dd3149/e1f6f32/storage-proofs/src/layered_drgporep.rs:495 storage_proofs::layered_drgporep
```

**Comment by dignifiedquire** [comment] 2019-07-01 08:40
- I can definitely replicate it on multiple machines
- switching to size `1024` in `main.sh` triggers the issue as well and is much faster to test
- reverting 4d520ea247eaebbc06ae1cca28cfc49cf1f2b4c4 fixes the issue (this is merkletree@0.7)

**Comment by nicola** [comment] 2019-07-01 10:58
Note: replication should take about 2h+

**Comment by schomatis** [comment] 2019-07-01 12:05
> * reverting [4d520ea](https://github.com/filecoin-project/rust-fil-proofs/commit/4d520ea247eaebbc06ae1cca28cfc49cf1f2b4c4) fixes the issue (this is merkletree@0.7)

@dignifiedquire Let's revert then.

> Note: replication should take about 2h+

@nicola I'm not saying that it _shouldn't_ (I'm sorry if it came across that way), I was mentioning it for reproducibility purposes only.

**Comment by dignifiedquire** [comment] 2019-07-01 18:57
failing test https://github.com/filecoin-project/merkle_light/pull/23

**Comment by schomatis** [comment] 2019-07-01 20:07
Fixed in same PR.

(Note that due to the non-deterministic nature of the new parallel implementation the length manipulation error didn't always manifest itself as it depended on the order it was written to the store).

**Closed** 2019-07-01 20:48 UTC
Labels: bug
