### ISSUE TITLE
PoSt not accepted by the network due to taking too long

### ISSUE THREAD

**Issue by steven004** [filecoin-project/rust-fil-proofs#738] opened 2019-07-13 09:58 UTC
I have a bunch of sealed sectors, more 500. And the system had successfully done PoSt, however, it is not accepted by the network and it states PoSt generation was too slow. 

`16:43:28.459 ^[[31mERROR ^[[0;34m/fil/stora: ^[[0mfailed to calculate PoSt: PoSt generation was too slow height=7255 end=6771 ^[[0;37mminer.go:772`

Btw, the PoSt took about 16 hours, that means from start to end, the chain height might grow more than 1000. 
And there is no way to recover, the miner is to be removed from the network forever.  

### Acceptance criteria
If there are too many sectors to be proved, there should be a way to partially done. 
Even over 1000 blocks, there might be some slashing, but there is a way to let the miner survive. 

### Where to begin
It's better to have PoSt being done in parallel; or let users choose set to be proved.

**Comment by embedSky** [comment] 2019-07-15 04:43
how many sectors did you sealed ,and what's your CPU？

**Comment by taylorshuang** [comment] 2019-07-15 05:53
This problem is widespread.

**Comment by anorth** [comment] 2019-07-17 04:45
Reporting to the stats dashboard at the moment, there are 31 miners who have proven exactly 1 sector. About twice that number have successfully proven more (tho many of these are probably owned by a few operators). So it must work sometimes.

@taylorshuang I see miner address/peer `t2cep62mi33uaaqstuvw7g4qj3ibn7jj6uva3cr5i | QmUyDWSqGYgQasFZkaLzZLGF36oYwVmzpBPyqK7U7kv8fk` bearing your name is claiming 10GB - did you resolve something?

**Comment by taylorshuang** [comment] 2019-07-17 08:16
Yes, the problem is very serious. I have two miners, one is taylorshuang Top, and the other is taylorshuang. taylorshunagTop, which is slightly normal. You can see that the data is increasing. However, data sometimes increases, sometimes does not. taylorshuang, this miner is totally abnormal.The difference between the two miners is that one has an external network IP and the other has no external network ip.

**Comment by taylorshuang** [comment] 2019-07-17 08:18
@anorth In addition, I found go-filecoin very unstable and often dropped. So, I wrote a daemon with golang, which can automatically identify program drops and restart automatically.

**Comment by taylorshuang** [comment] 2019-07-17 08:22
![image](https://user-images.githubusercontent.com/1488931/61359430-de5e2b00-a8ae-11e9-9f45-6e5f745b937f.png)
Obviously, the program dropped very seriously. In my opinion, if the program is unstable or not online during the effective period, it may cause PoST to be unacceptable.

**Comment by taylorshuang** [comment] 2019-07-17 08:25
But I found that some miners have a lot of calculating power, and I'm confused about what they can do. Now, I have two miners, using 20 other servers to produce data, and found that no good data can be obtained.

**Comment by taylorshuang** [comment] 2019-07-17 08:26
One reason is that it is unfair that participants are not familiar with the official rules for mining.

**Comment by mishmosh** [comment] 2019-07-17 22:30
> One reason is that it is unfair that participants are not familiar with the official rules for mining.

@taylorshuang do you mean rules such as relationship of sealed sectors to storage power, deadlines for submitting PoSts, et cetera? Is there anything else you would like to know?

cc @michellebrous @eshon

**Comment by taylorshuang** [comment] 2019-07-18 00:41
Obviously, the Post module is very unstable now, so you can see slack specifically. @mishmosh

**Comment by taylorshuang** [comment] 2019-07-18 00:41
The submitted data is not really reflected in the dashboard.

**Comment by steven004** [comment] 2019-07-18 01:42
I need to clarify this issue is trying to express there is a ceiling of proven power for each miner, due to PoSt generation taking a long time, once it exceeds 1000 blocks, then the miner will stuck there.

**Comment by travisperson** [comment] 2019-07-18 21:04
@laser I believe this is related to #615.

**Comment by steven004** [comment] 2019-07-26 03:20
I would think this is a high-priority issue. With the change of POST_SECTORS_COUNT, there would be sufficiant test being done before the next release launch. 

Do we have a plan to fix this recently? @laser

**Comment by laser** [comment] 2019-07-26 10:38
Yes, I do. 

Note that our PoSt construction is changing, so the work will come in two steps:

- increase the PoSt sectors count that our current (bogus) construction uses, which addresses this bug
- replace the existing PoSt construction with Rational PoSt

**Comment by laser** [comment] 2019-07-27 20:43
@travisperson - I have completed an upstream fix for this issue, trackable [here](https://github.com/filecoin-project/rust-fil-proofs/pull/762). Once that merges, I will update all relevant downstream projects (including go-filecoin).

**Comment by steven004** [comment] 2019-08-07 02:27
> @travisperson @steven004 - I have completed an upstream fix for this issue, trackable [here](https://github.com/filecoin-project/rust-fil-proofs/pull/762). Once that merges, I will update all relevant downstream projects (including go-filecoin).

The [PR](https://github.com/filecoin-project/rust-fil-proofs/pull/762) is closed, and looks the change is not in the master code. Do we still plan to have this change into 0.4 version, or just keep it due to more PoSt change might happen next.

**Comment by laser** [comment] 2019-08-07 02:54
@steven004 

> or just keep it due to more PoSt change might happen next.

Great question. @dignifiedquire: Should we scramble and write a temporary patch that addresses this issue - or wait until Rational PoSt lands (and remove `POST_SECTORS_COUNT` entirely)?

**Comment by dignifiedquire** [comment] 2019-08-07 10:17
@laser given that code freeze is about to hit the release for go-filecoin and the simple patch you wrote originally did not work out, I don't see a good way of patching this for the 0.4 release.

**Comment by mishmosh** [comment] 2019-08-07 15:33
The Aug 9 target is not a full code freeze, but rather a "no new risky features" to allow longer testing time (at longer chain length). Code freeze date is Aug 16. @dignifiedquire does that change your recommendation?

**Comment by dignifiedquire** [comment] 2020-03-02 14:23
fixed and resolved in latest versions

**Closed by dignifiedquire** 2020-03-02 14:23 UTC
